version: "3.5"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - djfy
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555"
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - djfy

networks:
  djfy:
    driver: bridge
